services:
  sunshine-steam:
      build: .
      container_name: sunshine-steam
      privileged: true
      shm_size: 2g
      environment:
        - TZ=America/Belem
        - SUNSHINE_USER=admin
        - SUNSHINE_PASS=admin
      ports:
        - "8080:8080"
        - "47984-47990:47984-47990/tcp"
        - "48010:48010/tcp"
        - "47998-48000:47998-48000/udp"
      volumes:
        - ./data:/home/gamer
        - ./games:/games
        - /dev/input:/dev/input:ro
        - /dev/uinput:/dev/uinput
        - /run/udev:/run/udev:ro
        - ./intel-xorg.sh:/usr/local/bin/generate-xorg-config:ro
      devices:
        - /dev/dri:/dev/dri
      restart: unless-stopped
  moonlight-web:
    image: mrcreativ3001/moonlight-web-stream:latest
    container_name: moonlight-web
    network_mode: host
    environment:
      - BIND_ADDRESS=0.0.0.0:8081
      - SSL_CERTIFICATE=/moonlight-web/server/moonlight-cert.pem
      - SSL_PRIVATE_KEY=/moonlight-web/server/moonlight-key.pem
    volumes:
      - ./moonlight-state:/moonlight-web/server
    restart: unless-stopped